server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: git@github.com:xiaolajiyhy/configture.git
          search-paths:
            - springcloud-config
      label: master #分支
  #rabbitmq位置
  rabbitmq:
    host: 123.57.36.75
    port: 5672
    username: guest
    password: guest


management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"
eureka:
  client:
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/


