server:
  port: 7002
eureka:
  instance:
    hostname: eureka7002.com #eureka 服务器实例名称
  client:
    register-with-eureka: false #不注册
    fetch-registry: false #不需要别人的服务，不查找
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000 #驱逐的时间
    peer-node-read-timeout-ms: 3000