server:
  port: 8089
spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://123.57.36.75/db2019?useUncode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456146a
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.entities
