server:
  port: 8802
spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders:
        defaultRabbit:  #设置Binder
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 123.57.36.75
                port: 5672
                username: guest
                password: guest
      bindings:
        input:
          group: atguiguA
          destination: studyExchange  #exchange名称
          content-type: application/json
          binder: defaultRabbit  #发个defaultRabbit

eureka:
  client:
    register-with-eureka: true #注册
    fetch-registry: true #查找别人的服务，
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id:  cloud-stream-provider